### ISSUE TITLE
Shared directory for session file storage

### ISSUE THREAD

**Issue by iverberk** [natecraddock/sessions.nvim#1]
Hi @natecraddock,

Thanks for creating this plugin. I'm happily using it in conjunction with workspaces and but noticed that the session file is always stored relative to the current cwd. I'd rather not pollute my workspace with neovim session information. It's not something I will commit nor will it be of interested to my fellow colleagues.

Is there a way to have sessions stored the same way as workspaces? Meaning that the 'data' + $SOMEDIR directory will be used to write session files, with filenames that match the current cwd?

**Comment by natecraddock** [comment]
Hi! Glad the plugins help you out! I will take a closer look at this later today (I had considered this before and I _think_ it wouldn't be hard to add, but I haven't touched the code in a couple months so...)

But in the meantime, have you considered [adding a global .gitignore](https://git-scm.com/docs/gitignore)? I have `.nvim/` in my global gitignore file and I never notice the hidden .nvim directories.

**Comment by iverberk** [comment]
Using a global .gitignore could certainly be an option to at least not see the folder (sometimes there are enough folders already). If it's not too much trouble it would be a great addition for me, and hopefully others. If it is a lot of work let me know why and I'll try to see if I can help out.

**Comment by natecraddock** [comment]
I took a closer look and it shouldn't be too hard. Here's my thoughts on how to add the feature in a backwards-compatible way:

1. Add a new config option `absolute` (default to false). When true the `session_filepath` is treated as an absolute directory.
2. Because the absolute directory would imply name conflicts between sessions (as you noticed), save the session file as the absolute path to the cwd converted to a filename
3. Loading a session is converting the cwd to the filename and loading that session file

I am a bit busy these next few days, but I _will_ work on it soon! Let me know if that makes sense or if you have suggestions for a better config

**Comment by iverberk** [comment]
That sounds just fine to me, nice and clean! Looking forward to start using it and no rush, take your time.

**Comment by natecraddock** [comment]
Turns out things were easier than I thought! If you would like you can try this branch https://github.com/natecraddock/sessions.nvim/tree/session-path-absolute and let me know if it works. I've tested and everything works fine! My config when I tested:

```lua
session_filepath = vim.fn.stdpath("data") .. "/sessions",
absolute = true,
```

I'll add some documentation and merge it soon

**Comment by iverberk** [comment]
Works like a charm, no more workspace 'pollution'! :-) Thanks for the quick turnaround.

**Comment by natecraddock** [comment]
Great to hear! I just merged the branch!
