### ISSUE TITLE
Implement post and pre hooks

### ISSUE THREAD

**Issue by aemonge** [natecraddock/sessions.nvim#11]
```
local function save_terminal_info()
    vim.notify("Terminal info saved: ", vim.log.levels.INFO)
end

local function restore_terminals()
    vim.notify("Terminal relaod: ", vim.log.levels.INFO)
end

local opts = {
    events = {},
    session_filepath = "/home/aemonge/.local/share/nvim/sessions/",
    absolute = true,
    pre_save_cmds = {
        function()
            vim.g.saved_terminal_info = save_terminal_info()
        end,
    },
    post_load_cmds = {
        function()
            restore_terminals() -- Your post-load logic here
        end,
    },
}

return {
    "natecraddock/sessions.nvim",
    lazy = false,
    config = function()
        require("sessions").setup(opts)
    end
}
```

Implementing this, would help me to keep the `pwd` of my terminal buffer on session save/restore

**Comment by natecraddock** [comment]
Hi there! So sorry for the lack of reply

I'm no longer maintaining sessions.nvim (I don't use it anymore). I try to fix bugs if they are found, but I'm not adding new features myself because I don't have the time.

If you happen to add this feature and make a PR I'm happy to review and merge

Sorry about that

**Comment by aemonge** [comment]
Ohh, I see :)

I'll switch to mini.session, it's also pretty small and focused. Thanks for the support given during this months <3
